name: Deploy madralo.pl

on:
    push:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy using ssh
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  port: ${{ secrets.PORT }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.PRIVATE_KEY }}
                  script: |
                      cd /root/services/SOK-client/
                      git pull origin master
                      cd /root/services/
                      docker compose up -d --build madralo-client
                      docker compose restart nginx
